### ISSUE TITLE
filesize footprint.  possible usage with preact?

### ISSUE THREAD

**Issue by rileylnapier** [coatue-oss/react2angular#16]
i'm interested in this project but im concerned with bundling react into my angular app.

do you know at all what the footprint of this is?  would it work with a smaller library like preact the same?

**Comment by bcherny** [comment]
Hey @rileylnapier - since react2angular doesn't actually bundle the React library into its dist files (it just references it with a `require`), you should be able to use [preact-compat](https://github.com/developit/preact-compat).

For an example, see https://github.com/developit/preact-compat-example.

**Comment by bcherny** [comment]
Closing this - @rileylnapier please reopen if you run into any issues on react2angular's side.
