### ISSUE TITLE
pass functions bindings wrapped in $scope.$apply

### ISSUE THREAD

**Issue by chiptus** [coatue-oss/react2angular#32]
Thanks for the great work!

If I pass functions to the component I need to wrap them with `$scope.$apply`, it would be nice if the module would check `propTypes` and wrap the right props with `$scope.$apply`

**Comment by bcherny** [comment]
Thanks @chiptus!

I don't think we want to go down this route. What if the consumer already wrapped their function in scope.$apply? We'd have to then wrap the $apply that we added in a try/catch, which is not ideal (it would fail to throw legitimate errors, and it would prevent V8 from optimizing the code in many cases).

**Comment by Aaron-Pool** [comment]
Sorry, to resurrect an old issue, but might `$evalAsync` be a good candidate for this? It will use a digest cycle if one is already in progress, but will trigger one if it isn't. So, it shouldn't matter if the user already wrapped the function call in `$scope.$apply`.

**Comment by chiptus** [comment]
I think this is best handled by the user of the library

**Comment by jamesz** [comment]
Existing behaviour can still be retained while giving the option to $applyAsync, or $evalAsync through an optional `options` parameter at the end with say two boolean optional keys applyAsync and evalAsync. I don't think $apply should be an option for reasons already discussed above.

We ended up forking in order to add this functionality, but as I imagine many other users of this library would probably want to avoid having to fork as well. Adding this option seems like useful functionality without any downsides.
