### ISSUE TITLE
Click events don't trigger Angular digest cycle?

### ISSUE THREAD

**Issue by jbkly** [coatue-oss/react2angular#39]
I'm testing the waters with using react2angular to start migrating parts of a large Angular 1.5 app to React. It seems that while you can pass functions from a parent angular component into a react2angular component, click events don't trigger the Angular digest cycle, forcing you to manually trigger scope.$apply() if you want Angular to re-render. Any ideas on a better way to handle this with react2angular?

Parent controller:
```
parentControllerMethod() {
  console.log('do something in the parent');
  // set some value that shows/hides something
}
```
Parent template:
```
<my-react-component
  on-trigger="vm.parentControllerMethod"
></my-react-component>
```
React component:
```
const myReactComponent = (props) => (
  <div>
    <button onClick={() => props.onTrigger()}>Trigger Something</button>
  </div>
);
```
When I click the button, `parentControllerMethod` will be called, but the UI doesn't re-render unless I then do a `scope.$apply()`.

**Comment by bcherny** [comment]
Hey @jbkly! That's right - events/HTTP requests/etc. won't trigger an $apply, same as if you had triggered that event from within a regular Angular component but had registered a listener with `addEventListener` rather than `ng-click`. Two solutions come to mind:

1. Call `$scope.$apply` from `parentControllerMethod`
2. Call `$rootScope.$apply` from `myReactComponent#onClick`:

```js
import {$rootScope} from 'ngimport'

// reusable helper
function withApply(fn) {
  return function() {
    $rootScope.$apply(() => fn.apply(this, arguments))
  }
}

const myReactComponent = (props) => (
  <div>
    <button onClick={withApply(props.onTrigger)}>Trigger Something</button>
  </div>
);
```

**Comment by jbkly** [comment]
Much appreciated, thanks!
