### ISSUE TITLE
Form validation in react and angularjs

### ISSUE THREAD

**Issue by HashemKhalifa** [coatue-oss/react2angular#45]
Hello, 
Container form component in angularjs and I need to migrate one by one.
for example.
payment page contains:
- contact details form.
- credit card form. 
- guest form.

so the point now I migrated guest form and validation works fine. but I need to map the validation on click the payment button which inside the parent component.

P.S using `formsy-react`

there any way to map between two validation angular and react on submit?

**Comment by bcherny** [comment]
Hi @HashemKhalifa! It's hard to give better advice without seeing your code, but because React doesn't have first-class controllers like Angular does, you might want to build an Angular shim layer between your React input and Angular, exposing `value` and `onChange` from the React component to the Angular shim. Alternatively, you can first migrate your Angular code away from ngModel/validators/formatters, and then convert it to React more easily.

If that doesn't answer your question, feel free to post your code and reopen this issue.
